#!/bin/bash

SERVICE_NAME=rpibeacon

function build {
    mkdir -p bin/darwin
    go build -o bin/darwin/$SERVICE_NAME
}

function build:rpi {
    mkdir -p bin/arm
    env GOOS=linux GOARCH=arm GOARM=5 go build -o bin/arm/$SERVICE_NAME
}

function build:release {
    mkdir -p bin/arm
    BUILD=$(date -u +%Y%m%d.%H%M%S)
    VERSION=${1:-$(git describe --abbrev=0 --tags)}
    echo "go build ldflags -X main.VERSION=$VERSION -X main.BUILD=$BUILD"
    env GOOS=linux GOARCH=arm GOARM=5 go build -ldflags "-X main.VERSION=$VERSION -X main.BUILD=$BUILD" -o bin/arm/$SERVICE_NAME 
}

function build:mv {
    local version=$1
    local user=${2:-pi}
    local host=${3:-raspberry}

    build:release $version

    ssh pi@openberry.local -C "sudo systemctl stop rpibeacon.service"
    scp rpibeacon pi@openberry.local:/home/pi/CODE/rpibeacon/
    ssh pi@openberry.local -C "sudo systemctl start rpibeacon.service"
}

function kk {
    local url=$(curl https://golang.org/dl/ | grep armv6l | sort |  grep -o -E "https://dl.google.com/go/go[0-9]+\.[0-9]+((\.[0-9]+)?).linux-armv6l.tar.gz")
    echo $url
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | grep -v '^_' | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-help}